[package]
authors = [""]
edition = "2018"
name = "app"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
log = "0.4.14"
sycamore = "0.5.0-beta.1"
sycamore-router = "0.5.0-beta.1"
wasm-bindgen = "0.2"

[dependencies.web-sys]
features = ["HtmlInputElement", "InputEvent"]
version = "0.3"
